### ISSUE TITLE
Window Undefined in Next.js

### ISSUE THREAD

**Issue by NicestRudeGuy** [srigar/multiselect-react-dropdown#107]
This error is from import only , ig this package check for window before even importing.
`{typeof window !== 'undefined' && ( <Multiselect options={optionTags} isObject={false} /> )}`
![image](https://user-images.githubusercontent.com/9863419/109801856-0dbcd980-7c45-11eb-9ae9-3cdf3af9d433.png)

**Comment by srigar** [comment]
It has been fixed in version >=2.0.0. Feel free to reopen issue if still persist
