### ISSUE TITLE
Search box icon updates

### ISSUE THREAD

**Issue by kodeman14** [srigar/multiselect-react-dropdown#111]
Would it be possible to update the icons for each chip, so that we can use any generic Material icon?
Also, can we get an optional icon for the left side of the box, like a search icon (magnifying glass)?

**Comment by srigar** [comment]
Currently in >=2.0.0, we have an option to pass custom close icon for chip and it will be common for all chip.

http://localhost:6006/?path=/story/multiselect-dropdown--custom-close-icon
