### ISSUE TITLE
Search functionality is not working in single select

### ISSUE THREAD

**Issue by adityadhage9** [srigar/multiselect-react-dropdown#117]
Unable to search through the options when single select is enabled.

**Comment by srigar** [comment]
Currently there is no search option in single select, will work on that

**Comment by srigar** [comment]
Adding feature as part of v3.0.0, for now closing this ticket and added in roadmap

**Comment by dawalberto** [comment]
@srigar Do you know when it would be solved? thank you =)

**Comment by ahmedfeki** [comment]
we need the search option for single select for api calls
