### ISSUE TITLE
Single select with preselected values

### ISSUE THREAD

**Issue by pakakornsitthisak** [srigar/multiselect-react-dropdown#12]
Hi Guys,

Thanks for awesome multiselect.

I have found one case when I put options ['A','B','C'] with preselected value 'A' and single select flag true. Once the dropdown shows up with preselect value 'A', the dropdown only shows ['B', 'C'] which is expected. However, when you select 'B' or 'C', the dropdown never show 'A' in the options. Also, 'B' or 'C' are still there.

Is this expected or not?

**Comment by srigar** [comment]
For single select, selected option will not get removed from options list. Issue fixed in 1.3.2
