### ISSUE TITLE
how to change color when i hover the option

### ISSUE THREAD

**Issue by erwin-d-austria** [srigar/multiselect-react-dropdown#120]

**Comment by NishitWappnet** [comment]
For now 
`.multiselect-container li:hover {
  background: #00aea766 !important;
  color: #fff;
  cursor: pointer;
}
.highlightOption {
  background: #00aea766;
  color: #ffffff;
}`

**Comment by srigar** [comment]
`/* Overriding element hover */
.optionContainer li:hover,
.optionContainer .highlight {
  background: red;
  color: #fff;
}
/* Ends overriding */

/* Placehoolder Color Change */
.searchBox#css_custom_input::placeholder {
  color: red;
}`

**Comment by sarahesteves** [comment]
Hi. I still can't change color for option hover... I added that code to my sass file, but my Multiselect component is not reading it. It just read the customization I made in the prop "style" inside the component. What am I doing wrong?

This is my component:

<Multiselect
              avoidHighlightFirstOption
              closeOnSelect={false}
              emptyRecordMsg="Sem opções disponíveis"
              isObject={false}
              onRemove={function noRefCheck() {}}
              onSearch={function noRefCheck() {}}
              onSelect={function noRefCheck() {}}
              options={options}
              placeholder="Pesquisar..."
              id="css_custom"
              style={{
                chips: {
                  background: 'transparent',
                  marginTop: '5px',
                },
                optionContainer: {
                  border: '1px solid #BEC7D8',
                  background: '#343442',
                  color: '#dee3eb',
                  fontSize: '12px',
                },
                searchBox: {
                  color: '#dee3eb',
                  fontSize: '12px',
                  fontWeight: '400',
                  borderColor: '#F1F2F6',
                  'border-radius': '0px',
                },
                option: {
                  borderBottom: '1px solid #BEC7D8',
                  marginRight: '10px',
                  marginLeft: '10px',
                  paddingTop: '5px',
                  paddingBottom: '3px',
                },
              }}
            />
            
This is my sass file:

.multiselect-container li:hover
  background: #FFF !important
  color: #000
  cursor: pointer

.highlightOption
  background: #000
  color: #fff

**Comment by TobiasKC** [comment]
Even though this is closed I had some trouble. Figured it out but you need to apply the !important class on the .option:hover class (in actual css file): 

//index.css 
.option:hover{
  background-color: white !important
}
.option{
  background-color: blue;
}
