### ISSUE TITLE
Concatenated string in displayValue

### ISSUE THREAD

**Issue by Azarchaniel** [srigar/multiselect-react-dropdown#123]
Hello, I have an array of objects like this: 
`[{
  firstName: 'John',
  lastName: 'Doe',
  nationality: 'us',
  ...
}];`
I want to show options in dropdown like this: 'Doe, John', therefore `{lastName + ', ' + firstName}`.
How can I do that? I tried to use arrow functions, but I didn't get any output.

**Comment by srigar** [comment]
Currently runtime we cant construct the display value. So before passing options need to construct it.
