### ISSUE TITLE
First dropdown value is always getting highlighted.

### ISSUE THREAD

**Issue by jeffDX619** [srigar/multiselect-react-dropdown#126]
Please see the screenshot below.

<img width="429" alt="Screenshot (4)" src="https://user-images.githubusercontent.com/56828393/120595558-3761e880-c460-11eb-874e-2f24d31c696c.png">

When I am hovering the mouse over 'Option 4' , the 'Option 1' is also getting highlighted.

**Comment by mitul-alliancetek** [comment]
You can use 

avoidHighlightFirstOption={true}
