### ISSUE TITLE
Property 'options' does not exist on type 'IntrinsicAttributes & { children?: ReactNode; }'.

### ISSUE THREAD

**Issue by webdevsmart** [srigar/multiselect-react-dropdown#131]
I am using Next.
import { useState } from "react";
import styled from "styled-components";

import dynamic from "next/dynamic";

interface MuliselectProps {
  options: any;
  displayValue: string;
}
const Multiselect = dynamic(
  () =>
    import("multiselect-react-dropdown").then((module) => module.Multiselect),
  {
    ssr: false,
  }
);
const data = [
  { key: "Option 1", cat: "Group 1" },
  { key: "Option 2", cat: "Group 1" },
  { key: "Option 3", cat: "Group 1" },
  { key: "Option 4", cat: "Group 2" },
  { key: "Option 5", cat: "Group 2" },
  { key: "Option 6", cat: "Group 2" },
  { key: "Option 7", cat: "Group 2" },
];
const MultipleOptionSelect = ({}) => {
  const [options1, setstate] = useState(data);
  return <Multiselect options={data} displayValue="key"></Multiselect>;
};

export default MultipleOptionSelect;
it has errors like this.

Type error: Type '{ options: { key: string; option: string; }[]; displayValue: string; }' is not assignable to type 'IntrinsicAttributes & { children?: ReactNode; }'.
  Property 'options' does not exist on type 'IntrinsicAttributes & { children?: ReactNode; }'.

**Comment by srigar** [comment]
Check in version 2.0.0 and dynamic import not required, SSR support added. Please feel to reopen issue if still issue persist
