### ISSUE TITLE
Prop 'showArrow' is not working properly

### ISSUE THREAD

**Issue by mfferreira** [srigar/multiselect-react-dropdown#136]
Reproduce:
1. Go to https://multiselect-react-dropdown.vercel.app/?path=/story/multiselect-dropdown--flat-array&args=showArrow:true
2. Make sure 'showArrow' is enabled
3. Instead of an arrow/chevron down, something that looks like a square is rendered (see below)

![Screenshot 2021-06-28 at 15 09 20](https://user-images.githubusercontent.com/882713/123641713-d3de9700-d822-11eb-95c9-c7405393c13f.png)

**Comment by srigar** [comment]
Changes available in v2.0.3

**Comment by alexyoung23j** [comment]
how can I install v2.0.3? Latest version yarn will install is 2.0.1

**Comment by srigar** [comment]
@alexyoung23j there was is a issue in CI/CD and got fixed.. Pls check now and use v2.0.4(latest one)

**Comment by alexyoung23j** [comment]
Im seeing that showArrow={false} seems to have no effect. Arrow still appears
