### ISSUE TITLE
Bundled CSS is overwriting CSS outside of component

### ISSUE THREAD

**Issue by fr31b3u73r** [srigar/multiselect-react-dropdown#137]
Since version 2 the bundled CSS is overwriting CSS outside of the component.
```
*, ::after, ::before {
  box-sizing: border-box;
}
```
This causes issues/additional work to fix when used in a React app that has different `box-sizing` set for other elements.

**Comment by srigar** [comment]
Will fix that...

**Comment by srigar** [comment]
Changes available in v2.0.15
