### ISSUE TITLE
Can't use onSearch()

### ISSUE THREAD

**Issue by anthony-ee** [srigar/multiselect-react-dropdown#139]
I have version 2.0.4 installed. The documentation lists "onSearch", but it's not a valid property when I try to set it on the Multiselect component.

`Property 'onSearch' does not exist on type 'IntrinsicAttributes & IntrinsicClassAttributes<Multiselect> & Pick<Readonly<IMultiselectProps> & Readonly<...>, "children" | "customCloseIcon"> & Partial<...> & Partial<...>'.`

**Comment by srigar** [comment]
Fix available in 2.0.5
