### ISSUE TITLE
selectedValues not working in General also before saving to DB

### ISSUE THREAD

**Issue by MuhammadRe** [srigar/multiselect-react-dropdown#14]
selectedValues doesn't work as expected, when is this issue will be solved, thanks

**Comment by srigar** [comment]
Can u explain the issue/scenario clearly?

**Comment by MuhammadRe** [comment]
`import React, { Component } from 'react';
import { Multiselect } from 'multiselect-react-dropdown';
import Form from 'react-bootstrap/Form';
import Col from 'react-bootstrap/Col';
import Row from 'react-bootstrap/Row';
import Button from 'react-bootstrap/Button';
import axios from 'axios';

let assignedLanguages = []

class CountryForm extends Component {
   constructor(props) {
      super(props)
      this.state = {
         countryName: '',
         languages: [],
         selectedLanguages: [],
         selectedvalues: [{key: "Nederland", id: "1"},
         {key: "German", id: "2"}],
         ...props.formData
      }
   }

   componentDidMount() {
      axios.get("http://localhost:3000/language")
      .then(res => {
         res.data.map(el => (
            assignedLanguages.push({key: el.languageName, id: el._id})
         ))
         this.setState({ languages: assignedLanguages })
      })
      .catch(err => console.log(err))
   }

   onSelect = (selectedItem) => {
      this.setState({ selectedLanguages: selectedItem })
   }

   handleChange = e => {
      e.preventDefault();
      this.setState({
         [e.target.name]: e.target.value
      })
   }

   render() {
      const { type, onSubmit, onCancel, onChange } = this.props;
      const isCreateNew = type === 'add';
      return (
         <div>
            <Form.Group className="row" style={{marginTop: "5%", marginBottom: "20px"}}>
               <Col sm={2}></Col>
               <Form.Label column sm={2} style={{marginTop: "5px"}}>Country name</Form.Label>
               <Form.Control type="text" name="countryName" value={this.props.formData? this.props.formData.countryName : this.state.countryName} placeholder="Type Country name" style={{marginLeft: "10px", width: "45%"}} onChange={isCreateNew? this.handleChange : onChange} />
            </Form.Group>
            <Form.Group className="row" style={{marginTop: "5%", marginBottom: "20px"}}>
               <Col sm={2}></Col>
               <Form.Label column sm={2} style={{marginTop: "22px"}}>Select language</Form.Label>
               <Multiselect
               options={this.state.languages}
               selectedvalues={this.state.selectedvalues}
               onSelect={this.onSelect}
               onRemove={this.onRemove}
               displayValue="key"
               />
            </Form.Group>
            <Form.Group as={Row} style={{textAlign: "center", marginTop: "5%", marginBottom: "5%"}}>
            <Col sm={6}>
               <Button variant="primary" onClick={() => onSubmit(this.state)} >{isCreateNew ? 'Add new' : 'Save changes'}</Button>
            </Col>
            <Col sm={6}>
               <Button variant="danger" onClick={onCancel} >Cancel</Button>
            </Col>
            </Form.Group>
         </div>
      )
   }
}

export default CountryForm;
`

**Comment by MuhammadRe** [comment]
`import React, { Component } from 'react';
import { Multiselect } from 'multiselect-react-dropdown';
import Form from 'react-bootstrap/Form';
import Col from 'react-bootstrap/Col';
import Row from 'react-bootstrap/Row';
import Button from 'react-bootstrap/Button';
import axios from 'axios';

let assignedLanguages = []

class CountryForm extends Component {
   constructor(props) {
      super(props)
      this.state = {
         countryName: '',
         languages: [],
         selectedLanguages: [],
         selectedvalues: [{key: "Nederland", id: "1"},
         {key: "German", id: "2"}],
         ...props.formData
      }
   }

   componentDidMount() {
      axios.get("http://localhost:3000/language")
      .then(res => {
         res.data.map(el => (
            assignedLanguages.push({key: el.languageName, id: el._id})
         ))
         this.setState({ languages: assignedLanguages })
      })
      .catch(err => console.log(err))
   }

   onSelect = (selectedItem) => {
      this.setState({ selectedLanguages: selectedItem })
   }

   handleChange = e => {
      e.preventDefault();
      this.setState({
         [e.target.name]: e.target.value
      })
   }

   render() {
      const { type, onSubmit, onCancel, onChange } = this.props;
      const isCreateNew = type === 'add';
      return (
         <div>
            <Form.Group className="row" style={{marginTop: "5%", marginBottom: "20px"}}>
               <Col sm={2}></Col>
               <Form.Label column sm={2} style={{marginTop: "5px"}}>Country name</Form.Label>
               <Form.Control type="text" name="countryName" value={this.props.formData? this.props.formData.countryName : this.state.countryName} placeholder="Type Country name" style={{marginLeft: "10px", width: "45%"}} onChange={isCreateNew? this.handleChange : onChange} />
            </Form.Group>
            <Form.Group className="row" style={{marginTop: "5%", marginBottom: "20px"}}>
               <Col sm={2}></Col>
               <Form.Label column sm={2} style={{marginTop: "22px"}}>Select language</Form.Label>
               <Multiselect
               options={this.state.languages}
               selectedvalues={this.state.selectedvalues}
               onSelect={this.onSelect}
               onRemove={this.onRemove}
               displayValue="key"
               />
            </Form.Group>
            <Form.Group as={Row} style={{textAlign: "center", marginTop: "5%", marginBottom: "5%"}}>
            <Col sm={6}>
               <Button variant="primary" onClick={() => onSubmit(this.state)} >{isCreateNew ? 'Add new' : 'Save changes'}</Button>
            </Col>
            <Col sm={6}>
               <Button variant="danger" onClick={onCancel} >Cancel</Button>
            </Col>
            </Form.Group>
         </div>
      )
   }
}

export default CountryForm;
`

**Comment by MuhammadRe** [comment]
as you can see i am using it as supposed to be but the values that has been selected don't show in the input like in example

**Comment by zfeof** [comment]
@srigar there is a typo in usage example in readme, should be "selectedValues" instead of "selectedvalues". Took me a while to notice this, I thought it wasn't working too.

**Comment by srigar** [comment]
Thanks. Will correct it ASAP
