### ISSUE TITLE
Remove value if entered text not found

### ISSUE THREAD

**Issue by aman-jeeves** [srigar/multiselect-react-dropdown#140]
How to remove value from textbox if the search item is not found ?

**Comment by srigar** [comment]
Are u asking about clear button in the end?

**Comment by amanopenxcell** [comment]
> Are u asking about clear button in the end?

@srigar No, For eg let's say it's multi option dropdown and we can search for values from dropdown, when the entered text is not found and we click outside or move to next field that searched text  is still present in that textbox ,actually it should be removed .

**Comment by srigar** [comment]
> > Are u asking about clear button in the end?
> 
> @srigar No, For eg let's say it's multi option dropdown and we can search for values from dropdown, when the entered text is not found and we click outside or move to next field that searched text is still present in that textbox ,actually it should be removed .

Gotcha, will fix that

**Comment by amanopenxcell** [comment]
Thanks

**Comment by D0HaTeJIJI0** [comment]
Have the same issue. Is this feature in development?

**Comment by srigar** [comment]
Changes available in v2.0.14
