### ISSUE TITLE
onBlur handler for the searchBox

### ISSUE THREAD

**Issue by jgudo** [srigar/multiselect-react-dropdown#143]
Is there an onBlur handler for the searchBox input? Can't seem to find it on the docs.

**Comment by ClintMathews1** [comment]
@jgudo I'm also stuck in a similar situation

![image](https://user-images.githubusercontent.com/54095355/132223390-ec237977-47d2-43e0-8993-395f16877027.png)
I need to clear the search value onBlur

Also I couldn't find a solution to this issue in the docs.

**Comment by hoang1510-dt** [comment]
@ClintMathews1 You could check out my solution to clear value in searchBox: https://stackoverflow.com/a/69078029/12508828

**Comment by srigar** [comment]
Changes available in 2.0.12. Onblur value will be cleared
