### ISSUE TITLE
Change color of the close icon

### ISSUE THREAD

**Issue by ahsan44411** [srigar/multiselect-react-dropdown#146]
I am using multiselect-react-dropdown. Is it possible to change the color of close icon?

<Multiselect
     style={{fontSize: 12}}
     options={children}
     selectedValues={paper.children_assigned_to}
     onSelect={(selectedList, selectedItem) => onSelect(selectedList, selectedItem, paper['id'])}
     onRemove={(selectedList, selectedItem) => onRemove(selectedList, selectedItem, paper['id'])}
     displayValue="name"
     closeIcon={"circle2"}
/>

**Comment by srigar** [comment]
Check custom close icon, 
https://multiselect-react-dropdown.vercel.app/?path=/docs/multiselect-dropdown--flat-array
