### ISSUE TITLE
Not working for keyboard

### ISSUE THREAD

**Issue by Hamzajoshan** [srigar/multiselect-react-dropdown#15]
It is not working for keyboard sir. if i enter a key from keyboard it is not working rather it sent me to the bottom of the page any solution if u have kindly provide ASAP. Thanku

**Comment by srigar** [comment]
Is that happening in multi select or single select?. Pls give the clear explanation or scenario.

**Comment by Hamzajoshan** [comment]
Sir it is happening in mutli select when i hit a key from keyboard to search anything then it's happened .

**Comment by danpalmer** [comment]
I can confirm that the keyboard interaction does not work at all when using the `groupBy` parameter. It does work for me when not grouping.
