### ISSUE TITLE
Convert the X and the Arrow images to font-awesome instead of images

### ISSUE THREAD

**Issue by orassayag** [srigar/multiselect-react-dropdown#159]
I can't replace the arrow color or style (Can do it with the close icon) - Why not just add "fontAwesomeIcon" attribute to add the icon we want for the arrow and the close icons?
For example:
closeIcon="fa-times"
arrowIcon="fa-arrow"

**Comment by srigar** [comment]
Cant support font-awesome, currently providing option to pass customCloseIcon. Try to leverage it.
