### ISSUE TITLE
MultiSelect showing me warning: Failed prop type: You provided a `checked` prop to a form field without an `onChange` handler. This will render a read-only field. If the field should be mutable use `defaultChecked`. Otherwise, set either `onChange` or `readOnly`.

### ISSUE THREAD

**Issue by jayna456** [srigar/multiselect-react-dropdown#16]
I am using this library for multiselect dropdown with check box. I am able to see dropdown and can select multiple options too.. And at the same time, I am getting the warning that **Failed prop type: You provided a `checked` prop to a form field without an `onChange` handler. This will render a read-only field. If the field should be mutable use `defaultChecked`. Otherwise, set either `onChange` or `readOnly`.**

This is my code: 
```
<Multiselect 
	options={OPTIONS_DATA}
	displayValue="key"
	showCheckbox={true}
	onSelect={this.onSelect}
/>
```
where OPTIONS_DATA is my array object and onSelect is my method..
Please help me out.. How can I fix this!!!!

**Comment by srigar** [comment]
Fix is available in @1.4.4
