### ISSUE TITLE
Property loading is missing in IMultiselectProps

### ISSUE THREAD

**Issue by AnotherCodeArtist** [srigar/multiselect-react-dropdown#168]
Asynchronous data loading can not be used, since the `loading` property is missing in type `IMultiselectProps`. Therefore, the typescipt compiler does not allow for this property.

There's already a [pull request](https://github.com/srigar/multiselect-react-dropdown/pull/167) fixing this issue.

**Comment by srigar** [comment]
Changes available 2.0.8
