### ISSUE TITLE
singleSelect selected value not showing in dropdown list

### ISSUE THREAD

**Issue by RohitParte** [srigar/multiselect-react-dropdown#174]
![image](https://user-images.githubusercontent.com/83939326/145678833-39a7208c-3c57-45dc-9b3d-97909d26d6ed.png)

It seems libray has too many issues but author is not interested in looking into it or may be busy with other things. It's not good to ignore the authored things because too many people using this packages and can have huge dependency on it and it's directly affects the cost of replacement of such packages.

@srigar

**Comment by srigar** [comment]
@RohitParte pls share me the code details. Its working in storybook
https://multiselect-react-dropdown.vercel.app/?path=/story/multiselect-dropdown--normal-single-select

**Comment by SmartNetAR** [comment]
In itself it can, but the element passed to it in selectedValues has to be an array.
