### ISSUE TITLE
No name property

### ISSUE THREAD

**Issue by Jackeysharath** [srigar/multiselect-react-dropdown#177]
Can you add name property?
It has id but there is no provision to set name?

**Comment by Jackeysharath** [comment]
I added it But not able to raise PR.

**Comment by srigar** [comment]
Added comment pls check it @Jackeysharath

**Comment by Jackeysharath** [comment]
I updated it,
Can you merge it now?

**Comment by srigar** [comment]
Changes available in v2.0.17
