### ISSUE TITLE
On blur of multiselect-react-dropdown it will remove searched text but in list it is showing only previously searched items.

### ISSUE THREAD

**Issue by viveksc1994** [srigar/multiselect-react-dropdown#180]
Issue - When we search any item by text, then click outside multiselect without clearing searched text. it will clear text but when we click on multiselect again it will show only items which are previously searched.

Demo - https://codesandbox.io/s/react-multi-select-dropdown-issue-nr4mh?file=/src/App.j
![react-multi-select-dropdown-issue---CodeSandbox](https://user-images.githubusercontent.com/10026278/147339549-ece915a8-4f5a-485a-b5aa-eda0108dc6ee.gif)

**Comment by srigar** [comment]
Changes available in v2.0.19
