### ISSUE TITLE
Can we disable other items on selected of particular item in the dropdown?

### ISSUE THREAD

**Issue by Shweta689** [srigar/multiselect-react-dropdown#189]
Thanks for the awesome library.
I just want to disable other items on selection of particular item.

Like if we are showing.

item1,
item2,
item2,
if select item1 the remaining 2 need to be disabled.

**Comment by srigar** [comment]
@Shweta689 currently we cant provide this option. Will keep it backlog as an enhancement. Closing this and keep it in track in backlog.
