### ISSUE TITLE
App crashing

### ISSUE THREAD

**Issue by AbinayaLakshmanan** [srigar/multiselect-react-dropdown#19]
![issue](https://user-images.githubusercontent.com/18413241/74245776-8d5dca80-4d09-11ea-98ae-aed4ec1b6d33.PNG)

![issue](https://user-images.githubusercontent.com/18413241/74246162-18d75b80-4d0a-11ea-84ba-116f2f30511e.PNG)

Library crashes when user selects an option and it's reproducible in your https://codesandbox.io/s/10xn41w767 too

**Comment by srigar** [comment]
Can u explain the scenario?

**Comment by srigar** [comment]
@AbinayaLakshmanan  Unable to reproduce, but still added null checks in all places. Are you displaying any numeric list in dropdown?

Fix available in 1.4.5

**Comment by AbinayaLakshmanan** [comment]
No only displaying array of string value. Now app is not crashing after updating your package .

**Thanks**
