### ISSUE TITLE
Prevent hiding options at least when using checkbox

### ISSUE THREAD

**Issue by mriiad** [srigar/multiselect-react-dropdown#191]
Hello,

Congratulations for the great work and the good library.

Since it's a multiselect component, the user's need would be selecting many choices when displaying options.
That's why it could be a good idea to keep it displayed after selecting an option.

I'm open to collaborate if you agree with this idea.

**Comment by srigar** [comment]
@mriiad there is prop available for this, use `closeOnSelect` as false. Pls check docs for more information about prop details. If it doesn't help, pls reopen it.
