### ISSUE TITLE
Not working with React 18

### ISSUE THREAD

**Issue by anand-gautam-mangoscience** [srigar/multiselect-react-dropdown#206]
![image](https://user-images.githubusercontent.com/90894945/167098109-118f898f-d775-40de-8ffb-63efd0a8b4f7.png)

**Comment by srigar** [comment]
Pls give a try with version 2.0.22

**Comment by anand-gautam-mangoscience** [comment]
Hi Srigar, The installation error got fixed. But the library still has some errors.
![image](https://user-images.githubusercontent.com/90894945/167380356-3ef9ade4-e018-4225-9faa-67f1a7309005.png)
