### ISSUE TITLE
Dropdown multi-select with checkbox dismisses the options

### ISSUE THREAD

**Issue by manoj2589** [srigar/multiselect-react-dropdown#24]
Hi Srigar,

When you choose the multi select with checkbox mode and click on an option's checkbox, it hides the list immediately and adds the chip. It could be better if you let the user select all items without having to click on the drop down field to re-show the options.

Makes sense? Let me know how I can help.

~~
Manoj.

**Comment by srigar** [comment]
@manoj2589 pls try `closeOnSelect` props with value as false.
