### ISSUE TITLE
Each child in a list should have a unique "key" prop

### ISSUE THREAD

**Issue by hsaleem11** [srigar/multiselect-react-dropdown#30]
Hello,
I get this warning when using this library: 

**Warning: Each child in a list should have a unique "key" prop**

I added a unique key to each item I'm rendering in the dropdown, but this warning doesn’t go away. I also followed the examples you have, but this issue is still there. Are you providing a unique key for each item in the dropdown list in the source code?

**Comment by srigar** [comment]
@hsaleem11 All places key attr are there. Can u please share ur options JSON structure?

**Comment by hsaleem11** [comment]
Hello @srigar 

Here is an example of the JSON structure I am using:

{id: 0, value: "testValue", groupName: "testGroupName"}

The id's are unique for all options in my list. I also tried adding a "key" property to my JSON structure, but it still shows the same error. Also, I am populating the dropdown list inside the "componentDidMount()" function. Is my JSON structure correct, or am I using this wrong?

**Comment by queenielyk** [comment]
I am facing the same problem also. I found this problem will only exist if using parameter 'groupBy'

**Comment by hsaleem11** [comment]
Yes, if I remove the 'groupBy' parameter the error doesn’t show up anymore. However, I still need the items to be grouped. Does anyone know how to resolve this issue?

**Comment by jmsaucier** [comment]
https://github.com/srigar/multiselect-react-dropdown/blob/434b615e20d53ef6943280b6d5ff84f94c18023d/src/multiselect/multiselect.component.js#L303

<React.Fragment> needs a key prop passed to it. @srigar , I can open a PR for this if you would like.

**Comment by jmsaucier** [comment]
Went ahead and opened the PR since the change was small. 

https://github.com/srigar/multiselect-react-dropdown/pull/32

**Comment by hsaleem11** [comment]
Thanks for looking into this @jmsaucier, it looks like this should fix the issue. @srigar can you review and merge this PR?

**Comment by srigar** [comment]
Changes are available in @1.4.8
