### ISSUE TITLE
Is there a support for TypeScript ? if so how to handle reset and on change Events 

### ISSUE THREAD

**Issue by Mogadampalli-Jayanth** [srigar/multiselect-react-dropdown#31]
Can you please help on this ?

//constructor code 

 private multiselectRef: React.RefObject<HTMLSelectElement> 
    constructor(props:MyProps) {
        super(props);     
        this.multiselectRef= React.createRef();   
  }

//Method for 
 getSelectedValues=()=>{
               const a : HTMLSelectElement = this.multiselectRef.current as HTMLSelectElement ;
              a.resetSelectedValues();
      }

//component calling

<Multiselect 
                  options={handlerNames}
                  isObject={false}
                  placeholder="Select Channels "
                  avoidHighlightFirstOption
                  selectedHandlers={selectedHandlers}
                  ref={this.multiselectRef}
                 />

**Comment by Maniraj-Murugan** [comment]
What is the status of this issue? Whether the typescript support has been there or included? I am also unable to include multiselect-react-dropdown in typescript based react app..

**Comment by srigar** [comment]
@Maniraj-Murugan Working on multiple features for 2.0 release, but not releasing now, mostly January 2021 with all new features and performance improvement

**Comment by Tchekda** [comment]
> 0 release

Hi,  is there some progress ? Because still nothing as of today.
Are you planning on a separate @types package or include it directly in the main codebase ? 

Thanks in advance

**Comment by srigar** [comment]
types support added in v2.0.0
