### ISSUE TITLE
How to set fixed width of container or searchbox?

### ISSUE THREAD

**Issue by chhaosh** [srigar/multiselect-react-dropdown#34]
When the list is long and we selected too many options, searchbox/container become very long, any CSS style to limit/autowrap the selectedItems?

**Comment by srigar** [comment]
@chhaosh Pls check CSS Customization section in Readme.
https://github.com/srigar/multiselect-react-dropdown#6-css-customization
Let me know if it doesn't work.

**Comment by srigar** [comment]
If anything pls reopen it.
