### ISSUE TITLE
Issues with onBlur functionality

### ISSUE THREAD

**Issue by raiShikha** [srigar/multiselect-react-dropdown#36]
If we have a target element, say a Multiselect Dropdown, when we click into the element and then if we click outside of this element or any other element, the focus shift to recently clicked element but the previous dropdown remains open.

**Comment by srigar** [comment]
Scenario working fine [Link](https://10xn41w767.codesandbox.io/). Is any other scenario.

**Comment by srigar** [comment]
Not active. Closed
