### ISSUE TITLE
Props changed by reference when onRemoveItem is called

### ISSUE THREAD

**Issue by FMCorz** [srigar/multiselect-react-dropdown#38]
The following line modifies the `selectedValues` in place thus causing the props to be changed by reference and potentially affecting the calling code. If `splice` is needed, then a shallow copy of the variable should be made before.

https://github.com/srigar/multiselect-react-dropdown/blob/4f57622c2398d6b0ca307c7804ef55a914c158bf/src/multiselect/multiselect.component.js#L232

This is likely because `componentDidUpdate` does not make a shallow copy when assigning the value to the local state, while the `constructor` does.

Constructor:
https://github.com/srigar/multiselect-react-dropdown/blob/4f57622c2398d6b0ca307c7804ef55a914c158bf/src/multiselect/multiselect.component.js#L20

ComponentDidUpdate:
https://github.com/srigar/multiselect-react-dropdown/blob/4f57622c2398d6b0ca307c7804ef55a914c158bf/src/multiselect/multiselect.component.js#L91

**Comment by srigar** [comment]
Thanks for clear info.. Changes are available in v1.5.5
