### ISSUE TITLE
can we show selected option outside of search box, please suggest how can i do?

### ISSUE THREAD

**Issue by raj-barnwal** [srigar/multiselect-react-dropdown#40]

**Comment by srigar** [comment]
Please provide clear description with scenario.

**Comment by globefire** [comment]
Say three options were chosen. Let's assume that we are using an array of objects. We want to know what all items were selected. Now, this data can be used to send to some API or can be appended to some DOM elements. It's basically how to use the `getSelectedItems`. The docs have not provided a proper example of how to use it. @srigar 
CC: @raj-barnwal

**Comment by srigar** [comment]
U can use preselected values to display outside the dropdown.

**Comment by raj-barnwal** [comment]
Thanks Srigar
