### ISSUE TITLE
Duplicate id when using multiple Multiselects

### ISSUE THREAD

**Issue by ozzell** [srigar/multiselect-react-dropdown#41]
There is an id-attribute in the Multiselect-component, which is hard-coded and cannot be changed:

id="multiselectContainerReact"

So if you have two Multiselect-components on a page, then you also have two duplicate id:s on the page. This should be fixed since id:s have to be unique.

**Comment by srigar** [comment]
Fix available in v1.4.11. By using props id will solve the issue.
