### ISSUE TITLE
Input field scrolls to top of screen when search starts

### ISSUE THREAD

**Issue by ESeufert** [srigar/multiselect-react-dropdown#42]
When I type into the input field (to search), the screen scrolls such that the input field is at the very top of the screen. Any way to prevent this from happening?

(The same behavior happens in the demo code for the very first dropdown: as soon as you type a letter into the input field, the screen scrolls so that the input field is at the very top of the screen)

![image](https://user-images.githubusercontent.com/1784862/81483700-bb1db700-9205-11ea-99a6-ff9fe8256fd0.png)

**Comment by srigar** [comment]
Fix available in v1.5.0.
