### ISSUE TITLE
Unselect values without clicking on close icon 

### ISSUE THREAD

**Issue by ghassenchaar96** [srigar/multiselect-react-dropdown#43]
Hi, thank you for this helpful package.
I'm using the multiselect-react-dropdown as a catalog filter, and I wanted to know if there is a way to unselect values, not by clicking on the close icon of the selected value, but by clicking on my own filter tag.
Below is my example:
I have selected the 'Auto' value from the dropdown options.

![dropdown](https://user-images.githubusercontent.com/49613870/82196201-b2aa3800-98f9-11ea-808d-b8247cd4f788.png)

I want to unselect it by clicking on my own filter tag:

![dropdown1](https://user-images.githubusercontent.com/49613870/82196438-f9982d80-98f9-11ea-8202-dfcb68643c61.png)

Thank you !

**Comment by srigar** [comment]
@ghassenchaar96 In the below example, all selected values will be `this.state.selectedValues` and u can display any where. Also any changes in `this.state.selectedValues` will rerender multiselect component. For example, by removing any value from `selectedValues` will rerender the component

```
<Multiselect
options={this.state.options} // Options to display in the dropdown
selectedValues={this.state.selectedValue} // Preselected value to persist in dropdown
onSelect={this.onSelect} // Function will trigger on select event
onRemove={this.onRemove} // Function will trigger on remove event
displayValue="name" // Property name to display in the dropdown options
/>
```
