### ISSUE TITLE
Issue with search in Multiselect with checkbox 

### ISSUE THREAD

**Issue by kyomean** [srigar/multiselect-react-dropdown#45]
The issue happens in the example **5. Multiselect with checkbox**.

1) Open the list and type "3"
2) Click on "Option 3"
3) Open the list again and find just "Option 3" as available option (**bug**)
4) Type any character and delete it to show all the options again.

**Comment by vijeth123** [comment]
Hi, any update on this issue? Thanks

**Comment by srigar** [comment]
fix available in v1.5.4
