### ISSUE TITLE
Not able to change option background color on hovering over options inside optionContainer using style object

### ISSUE THREAD

**Issue by anandgupta193** [srigar/multiselect-react-dropdown#49]
The style object should gives us the capability to change the hover color for options.

**Comment by srigar** [comment]
@anandgupta193 we can override in our component itself by using classname provided my multiselect. Pls check example ["CSS Customization example"](https://10xn41w767.codesandbox.io/#css). Also find the css reference [here](https://codesandbox.io/s/10xn41w767?file=/src/styles.css)
