### ISSUE TITLE
 First Option in Dropdown is always highlighted

### ISSUE THREAD

**Issue by thewinger** [srigar/multiselect-react-dropdown#5]
I first noticed it in my project, but it also happens in  https://codesandbox.io/s/10xn41w767
The first option of the dropdown is highlighted by default when the expected behaviour would be to not have anything highlighted when nothing is yet selected.

**Comment by cis-lokesh** [comment]
I'm also facing the issue

**Comment by cis-lokesh** [comment]
I'm also facing the same issue

**Comment by srigar** [comment]
Will not highlight anything by default and get highlighted when the keyboard navigation start.
Fix available in v1.4.1

**Comment by srigar** [comment]
v1.4.7 highlighting first option is based on props. Because for different use case we need to highlight first option. So if u r using latest version please check `avoidHighlightFirstOption`. By default first one will be highlight.

**Comment by AdamElhawary** [comment]
**I fixed this using css:** 

.lhyQmCtWOINviMz0WG_gr{
    background: none !important;
    color: black !important;
}

.optionContainer .highlight:hover{
    background-color: "Your color if needed" !important;
}
