### ISSUE TITLE
Need ability to disable all user input

### ISSUE THREAD

**Issue by jschnurer** [srigar/multiselect-react-dropdown#51]
I need the ability to disable user input. A simple property named `disabled` could be sent that prevents any user interaction with the control. Right now, I am approximating this behavior by setting the `options` equal to the `selectedValues` and `disablePreSelectedValues` to `true`.

However, the dropdown still appears on click so I set the `emptyRecordMsg` to `""`. Unfortunately, it still appears but it is blank.

**Comment by srigar** [comment]
@jschnurer Use disable props to disable dropdown.
Changes are available in v1.5.2
