### ISSUE TITLE
How to use in JSX

### ISSUE THREAD

**Issue by rathoregee** [srigar/multiselect-react-dropdown#52]
can you please provide a sample?
We have below mentioned structure :)

`import React, { useEffect, useState, useCallback, useRef } from 'react';
import { hot } from 'react-hot-loader';
import { Multiselect } from "multiselect-react-dropdown";

const DropDown = () => {

  useEffect(() => {
  }, []);
  return (<h1>Hello</h1>);
}

export default hot(module)(DropDown)`

**Comment by abhidj0090** [comment]
you need to add a multi select fragment like this

<Multiselect
                                    id="id"
                                    options={options} // Options to display in the dropdown
                                    selectedValues={this.selectedValue} // Preselected value to persist in dropdown
                                    onSelect={this.selectChanged} // Function will trigger on select event
                                    onRemove={this.selectChangedRemove} // Function will trigger on remove event
                                    displayValue="name" // Property name to display in the dropdown options
                                    closeIcon="cancel"
                                />
