### ISSUE TITLE
onRemove is not called when item is backspaced out of search bar

### ISSUE THREAD

**Issue by jslucas** [srigar/multiselect-react-dropdown#59]
Removing a selected item from the search bar using backspace does not fire the `onRemove` callback.

<img width="600" alt="image" src="https://user-images.githubusercontent.com/22177563/87799032-bc2d1f00-c81a-11ea-9970-6a6d4c8a84f0.png">

Backspacing removes it from the search bar and unchecks the checkbox, however `onRemove` is not called

<img width="525" alt="image" src="https://user-images.githubusercontent.com/22177563/87799064-c818e100-c81a-11ea-958a-83959a88d1eb.png">

**Comment by srigar** [comment]
@jslucas looks like it is working fine,

https://drive.google.com/file/d/1ioVUN_Y0K7OodczQQbpftIlMV01llvVX/view
