### ISSUE TITLE
I need the text currently in text box to send request to server.

### ISSUE THREAD

**Issue by iIdiomatic** [srigar/multiselect-react-dropdown#61]
How to get text that is being typed in text box to trigger search at back-end.

**Comment by ayushk23** [comment]
@iIdiomatic Did you find any workaround for that? I have a similar requirement. So please share if you do.

**Comment by srigar** [comment]
Changes available in v1.6.0, supports callback function, on change in input field will trigger callback function called `onSearch` also it supports other props like `loading` and `loadingMessage`. Check props section for more details.
