### ISSUE TITLE
Dropdown closes on unchecking an item in the dropdown

### ISSUE THREAD

**Issue by DeepGunner** [srigar/multiselect-react-dropdown#65]
The dropdown collapses on unchecking an item in the dropdown, wondering if there's a property similar to closeOnSelect={true} for unchecking.

**Comment by srigar** [comment]
Fix available in v1.5.8, it uses same flag called closeOnSelect={false} so dropdown wont get close for unchecking

**Comment by DeepGunner** [comment]
Thanks for your help. Much appreciated.
