### ISSUE TITLE
Not able to select values from multiselect dropdown in Windows OS

### ISSUE THREAD

**Issue by mankii24** [srigar/multiselect-react-dropdown#66]
Browser: All

**Comment by elaine0304** [comment]
I'm facing the same problem. The options do not get selected if we tap on them. Only a mouse click selects the option.

**Comment by sfxoogundare** [comment]
@elaine0304 Have you fixed this issue?

**Comment by elaine0304** [comment]
@sfxoogundare No, since I didn't get any reply here, I went ahead and choose a different multi-select plugin.

**Comment by naveenrj98** [comment]
@elaine0304 could you please tell me which one did you choose other than this, I am facing the same issue

**Comment by elaine0304** [comment]
@naveenrj98 I choose [https://www.npmjs.com/package/react-select](url) this one.

**Comment by srigar** [comment]
@elaine0304 @naveenrj98 issue has been fixed available in version **v1.6.6** and feel free to reopen if u still face any issue.
