### ISSUE TITLE
ReferenceError: Can't find variable: document

### ISSUE THREAD

**Issue by mitjnextt** [srigar/multiselect-react-dropdown#67]
Facing this error, after installing the library...

`ReferenceError: Can't find variable: document`

"react": "16.9.0",
"react-native": "0.61.5",
 "multiselect-react-dropdown": "^1.5.7",

**Comment by srigar** [comment]
Duplicate #47 it fails in SSR due to style-loader, working on that, post u once done. For time being please check workaround in the ticket.

**Comment by srigar** [comment]
It has been fixed in version >=2.0.0. Feel free to reopen issue if still persist
