### ISSUE TITLE
Not working in chrome

### ISSUE THREAD

**Issue by bradc343** [srigar/multiselect-react-dropdown#68]
https://10xn41w767.codesandbox.io/ Your demo code does not work in chrome but work fine in edge. Was working 3 days ago. Any thoughts on why this is?

**Comment by bradc343** [comment]
Correction works but you have to double click it in chrome.. weird. but any thoughts?

**Comment by bradc343** [comment]
nevermind problem is on my end

**Comment by elaine0304** [comment]
Can you let us know what the problem was on your end?
It does not select the option on my windows machine.
