### ISSUE TITLE
My multiselect doesn't empty after uploading my form

### ISSUE THREAD

**Issue by paz873107** [srigar/multiselect-react-dropdown#70]
I've used the multiselect dropdown to assign multiple categories to a product in an e-commerce project. But when I upload the product form, all other inputs are empty except for the multiselect. Does anyone knows how to fix this?

**Comment by srigar** [comment]
If u r dng default form reset then it won't work, u can clear it by making the state array as empty or u can access the clear function by the help ref(check readme)

**Comment by paz873107** [comment]
Thank you so much, I was really looking forward to get this answer!
