### ISSUE TITLE
onSelect function is not working

### ISSUE THREAD

**Issue by chamodSamajith** [srigar/multiselect-react-dropdown#73]
<Multiselect
                                    options={lecturersArr}
                                    onSelect={(l,i) => onChangeLecture(l,i)}
                                    displayValue="name"
                                    id={`${lecturersArr._id}`}
                                />

**Comment by chamodSamajith** [comment]
selected values are not displaying the input field - same happens in your demo -https://10xn41w767.codesandbox.io/

**Comment by srigar** [comment]
@chamodSamajith It is working in demo
![image](https://user-images.githubusercontent.com/20384652/93602978-04b2b580-f9e1-11ea-81e8-d6b5e2567c5b.png)

**Comment by chamodSamajith** [comment]
@srigar  Chrome
