### ISSUE TITLE
Programmatically deselect selections

### ISSUE THREAD

**Issue by arpitnarechania** [srigar/multiselect-react-dropdown#8]
Is there a way to programmatically deselect manually set options?
In addition, is there a way to programmatically select options _AFTER_ the component has been loaded (selectedValues will still be empty).

If not, how and when can this be added?

**Comment by srigar** [comment]
Please clearly explain the scenario.

**Comment by srigar** [comment]
Feature added in the version 1.4.0. For more info, check readme file(#5)
