### ISSUE TITLE
Unable to Change the Background Color of Checkbox

### ISSUE THREAD

**Issue by jayacados** [srigar/multiselect-react-dropdown#84]
Hi there,

I've been digging through the source code and through the docs. Maybe I missed something, but I'm unable to find a way to change the background color of the checkbox. I've exhausted all potential options on my end and need some assistance to pinpoint how I would navigate through this. 

I've posted a visual below of what I'm aiming to go for. Essentially, the blue is the color I want to change. Any tips would definitely be appreciated!

<img width="44" alt="Screen Shot 2020-11-24 at 3 44 06 PM" src="https://user-images.githubusercontent.com/43162794/100164041-e4352a80-2e6b-11eb-9371-f4f882c87c65.png">

**Comment by srigar** [comment]
@jayacados  currently checkbox used default browser stylesheet. Soon going to release version 2.0, will consider to provide the color option for checkbox. Will keep it open till it get resolved.

**Comment by jayacados** [comment]
Thank you! Is there any way to override this in the meantime?

**Comment by victor-z-xiong** [comment]
@jayacados How did you manage to change the color of a dropdown item to be pink? When you hover over a dropdown option it's always blue (default colour) for me. 

I've tried setting

```
  multiSelectContainer: {
    "&:hover": {
      background: "#ea4c89"
    }
  }
```

and it remains the default colour.

**Comment by srigar** [comment]
@victor-z-xiong have to do it in css file. Refer demo implementation
https://codesandbox.io/s/10xn41w767?file=/src/styles.css:889-981

.optionContainer li:hover,
.optionContainer .highlight {
  background: red;
  color: #fff;
}

**Comment by srigar** [comment]
@jayacados No..

**Comment by ponpandiyan** [comment]
@victor-z-xiong do it in css file
give accent-color property for input checkbox

 accent-color: #002C50 !important;
