### ISSUE TITLE
Dropdown keeps flickering when closeOnSelect={false}

### ISSUE THREAD

**Issue by bhumikasukhadiya0901** [srigar/multiselect-react-dropdown#85]
I need to keep the dropdown menu open after select/de-select the option from the list, and for that i used closeOnSelect={false} but on select/de-select it is closing and opening so it keeps flickering.

[https://www.awesomescreenshot.com/video/1892407?key=ba2a69d1805ab7e882130b67e165cdce](url)

**Comment by bhumikasukhadiya0901** [comment]
@srigar Could you please have a look at this issue and provide some solution? I have used it in my project and it is giving me issue.

**Comment by srigar** [comment]
Duplicate #75
