### ISSUE TITLE
How to change placeholder text color?

### ISSUE THREAD

**Issue by simsandhu** [srigar/multiselect-react-dropdown#90]
Hello!

I'm currently trying to change the placeholder text color, however, everything I've tried keeps it to the default color which is gray. Is there a way to change the color?

Thanks!

**Comment by srigar** [comment]
@simsandhu with the help of custom ID or existing classname, u can change the placeholder color in css. Refer css customisation section for the implementation in the below demo link.

https://10xn41w767.codesandbox.io/#css
