### ISSUE TITLE
Single select is not working on selecting check box or text in chrome

### ISSUE THREAD

**Issue by naveenrj98** [srigar/multiselect-react-dropdown#96]
Hi, I am not able to Select the item with one click, have to double click the item to select, if I use the mouse and click its working for me, but with the laptop touchpad single select is not working, could you please help me with it or any suggestions to resolve this issue. @srigar

**Comment by srigar** [comment]
pls check with v1.6.6 and let me know if u still facing same issue. @naveenrj98

**Comment by naveenrj98** [comment]
Thank you, it's working fine now
