### ISSUE TITLE
Hide placeholder when there is a selection [feature request]

### ISSUE THREAD

**Issue by McBenny** [srigar/multiselect-react-dropdown#99]
This is a feature request, not a bug.

When the select is closed, if there is no value selected (whether it's preselected or not), display the placeholder.
If there is a/several value(s) selected, just show the value(s).

At the moment, the placeholder is shown or not but in both cases, no way to separate the cases as far as I could find.

Thanks for the good work already done!

**Comment by srigar** [comment]
@McBenny use `hidePlaceholder` property, if any selectedValues and hidePlaceholder property is true then placeholder wont display.

**Comment by McBenny** [comment]
Thanks @srigar , works perfectly, sorry I didn't see the feature before.
